name: Android Build
on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
      dotnet-version-targets:
        required: true
        type: string
      project-file:
        required: true
        type: string
      project-folder:
        required: true
        type: string
      build-config:
        required: true
        type: string
      build-version:
        required: true
        type: string
jobs:
  publish-android:
    runs-on: windows-latest
    name: Android Build
    steps:
      - name: Setup .NET ${{ inputs.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
      - uses: actions/checkout@v3
        name: Checkout the code
      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources
      - name: Restore Dependencies
        run: dotnet restore ${{ inputs.project-file }}
      - name: Build .NET Maui
        run: dotnet build ${{inputs.project-file}} -c ${{ inputs.build-config }} -f ${{ inputs.dotnet-version-target }}-android /p:AndroidPackageFormats=aab --no-restore
