name: Build Documentation
on:
  push:
    paths:
      - 'docs/**'

jobs:
  compile-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Pandoc and Pandoc-crossref
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc pandoc-crossref

    - name: Build Documentation
      run: |
        chmod +x ./docs/pdf.sh
        ./docs/pdf.sh
